seed: 0
setting: UDA
dataset: domainnet
backbone: ResNet50
bottleneck_dim: 256
max_iter: 10000
eval_interval: 500
class_num: 50
batch_size: 36
k: 5
temp: 0.05
smooth: 0.5
lam_con: 0.1
lam_mim:
  min: 0.05
  max: 0.1
